# Generated by Django 5.0.1 on 2024-01-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renting',
            options={'ordering': ['-date_rent']},
        ),
    ]
