# Generated by Django 5.0.1 on 2024-01-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_renting_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('5', 'Execellent'), ('4', 'Very good'), ('3', 'Ok'), ('2', 'Bad'), ('1', 'Very bad')], max_length=20),
        ),
    ]
