# Generated by Django 5.0.1 on 2024-01-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=150, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='county',
            field=models.CharField(max_length=150, null=True, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='user',
            name='post_code',
            field=models.CharField(max_length=150, null=True, verbose_name='Post Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='town',
            field=models.CharField(max_length=150, null=True, verbose_name='Town/City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='Address'),
        ),
    ]
