# Generated by Django 5.0.1 on 2024-02-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(default=False, max_length=200, upload_to=''),
        ),
    ]