# Generated by Django 5.0.1 on 2024-02-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_image_photo_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='main_app.category'),
        ),
    ]
